import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VetSync Animal Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Script id="show-banner">
          {`
            function loadWidget() {
              const script = document.createElement("script");
              script.src = "https://app.usevetsync.com/widget.js";
              script.async = true;
              script.onload = function () {
                console.log("Widget script loaded");
                if (window.PetBooking && typeof window.PetBooking.initializeWidget === "function") {
                  window.PetBooking.initializeWidget({
                    clinicId: "86d73c9f-20e4-4672-8933-4f32bcbdb18c",
                  });
                } else {
                  console.error("Widget initialization failed");
                }
              };
              script.onerror = function () {
                console.error("Failed to load widget script");
              };
              document.body.appendChild(script);
            }

            // Load the widget when the page is ready
            if (document.readyState === "loading") {
              document.addEventListener("DOMContentLoaded", loadWidget);
            } else {
              loadWidget();
            }
          `}
        </Script>
        {children}
      </body>
    </html>
  );
}
